= Elmgorithm
Browser based visualization of sorting algorithms using [Elm](https://elm-lang.org/).

== Visualized algorithms
All of the visualized algorithms are implemented recursivly.

* Bubble Sort
* Insertion Sort
* Merge Sort
* Quick Sort

== How to start
Elmgorithm was developed using the interactive development tool `elm-reactor`.
You can download and start the app by executing the following commands.

```
$ git clone https://github.com/Kluddizz/elmgorithm
$ cd elmgorithm
$ elm reactor
```
This will start a local server on port 8000 by default. Now, the app is
accessible visiting `http://localhost:8000/src/Main.elm`.

== How to use

. *Choose an algorithm.*
In settings click the dropdown menu and select an algorithm. You can read
more about the implementation and performance by clicking the question mark in
the animation control panel at the bottom of the application.

. *Insert a number of elements.*
In the settings select the input field labeled with _Elements_ and enter the
number of elements inside the list to be sorted. Be careful with the input
value. Some algorithms may be very slow and the application could freeze.

. *Generate random elements.*
In settings you can generate a new list using the _New Values_ button.

. *Calculate and play the animation.*
In settings you can start the calculation of the selected algorithm and play
the animation using the play button.

. *Watch the statistics and change the animation speed.*
While the animation is running you can observe some statistical information
on top of the animation display.
